[TFormMain]

XobList.Hint=Use right mouse button
FileItem=File
PSFileItem=PS-file
CmdFileItem=CMD-file
DmRepeatItem=Dm-repeat
MsRepeatItem=Ms-repeat
ExitItem=Exit
OptItem=Options
PsCfgItem=PS
MapIncludeItem=Use transparency property
HelpItem=Help
N2=Help content
N4=About program
XobAddItem=Add
XobInsertItem=Insert
XobDelItem=Delete
XobClear=Delete All
TabbedNotebook1.0=General
TabbedNotebook1.1=Page on map
TabbedNotebook1.2=Rect on map
TabbedNotebook1.3=Parameters
TabbedNotebook1.4=Sizes
Label4=Legends (.gc, .gcx)
Label3=Output PS-file
TextAsCurves=Text as curves
CheckShowPage=Add showpage
ColSep=Separation
ModeGroup.0=View (make PS)
ModeGroup.1=GS-Print
ModeGroup.2=Convert
ModeGroup.3=Windows-Print
MultiMsGroup=Insertions
MultiMsGroup.0=Non
MultiMsGroup.1=Over
MultiMsGroup.2=Below
BtnAi=Browse
OutFileClear=Clear
ButtonPage=Process page
GroupBox3=pages map
PageSizeFromBln=Size from blank
RotCheck=Page rotation
Label13=Zoom
ButtonClear1=Current map
BtnPageMap=Browse
Label9=Prefix of EPS-file
Label7=Internal margins
Label8=mm
Label2=Code of page
PortGroup.0=As a print page
PortGroup.1=Zoom calculation
PortGroup.2=Page calculation
ButtonShow=Process rect
Label5=Zoom
Label1=Map scale
ButtonScale=Current map scale
Markers=Markers
MarkersOffset=Markers Offset
Mirror=Mirror
Negativ=Negativ
Label10=Raster frequency (lpi)
Label11=Raster angle (0.1 degree)
Rotation=Rotation
Rotation.0=Non
Rotation.1=90 degrees
Rotation.2=180 degrees
PrintPNum=Print page number
PnumUp=At the top
GroupBox1=Page sizes (mm):
Label6=Margins
Label12=Page
px0.Hint=Left/Right margins
py0.Hint=Top/Bottom margins
pw.Hint=Width
ph.Hint=Height

[TFormPrnCnv]

FormPrnCnv=Print/Convert
Label5=Driver
Label4=Resolution (dpi)
ToFile=To File
ButtonSave=Browse
BtnOk=OK
BtnCancel=Cancel

[TColSepDlg]

ColSepDlg=Separation
Model=Color Model
Ok=Ok
Cancel=Cancel

[TPrintDlg]

PrintDlg=View/Print
mode=Mode
mode.0=View
mode.1=Print
mode.2=Add Preview Image
mode.3=Add "showpage"
AddShowpage=Add "showpage"
Label1=Zoom
OKBtn=OK
CancelBtn=Cancel

[TAboutForm]

AboutForm=About program
Label3=Program for print and pre-print processing the digital maps in system "Neva"
Label2=A.I.Pluzhnikov
Label4=Version 2005.1

[Tell]

0=No Legend
1=Zoom Error
2=Papet size Error
3=No active map
4=Blank's page size Error

5=Delete?
6=Command file "%s" executed
7=Error in command file "%s"
8=Names must be different:\n%s --> %s
9=File %s exists. Replace?

10=Error in open map
11=Page %d not found
12=Zero-size of the map's page
13=No file
14=Format error in command:\n<%s %s>
15=Set "Output PS-file" for output directory
16=Project file "%s" not found
17=Error in open project "%s"
18=Unknown command <%s> in file "%s"
19=No legend in insertion's attributes

20=Insertion's attributes error (file not found):\n%s\n%s\n%s'
21=Load error: msw.dll


[LIB:]

[TGsOptDlg]

GsOptDlg=PS options
GsBox=GSWIN32.EXE
LibBox=PSL.INI
Label1=
GsPathBtn=Browse
LibPathBtn=Browse

[TellLib]

0=Input path to %s
1=I can't open file "%s"
2=I can't create file "%s"
3=I can't delete file "%s"
5=Bad size in map "%s" (dm_Resolution)
6=Bad scale in map "%s" (lpmm)
7=No active map

